--UNA CONSULTA PUEDE DEVOLVER LOS MISMOS DATOS, PERO EXISTEN  

--CONSULTAS MÁS EFICIENTES (VELOCIDAD) QUE OTRAS 

select * from DEPT 

select DEPT_NO, DNOMBRE, LOC from DEPT 

--ORDENACION DE DATOS.  SIEMPRE IRA AL FINAL DE LAS CONSULTAS 

--ASC/DESC 

select * from EMP order by APELLIDO asc 

select * from EMP order by APELLIDO desc 

--FILTRADO DE DATOS 

--UTILIZAMOS LA PALABRA WHERE.  SOLAMENTE UN WHERE 

--OPERADORES RELACIONALES 

/* 

= IGUAL 

>= MAYOR O IGUAL 

< MENOR 

<= MENOR O IGUAL 

<> DISTINTO 

*/ 

--SI ESTAMOS COMPARANDO CUALQUIER DATO NO NUMERICO, SE UTILIZAN 

--LAS COMILLAS SIMPLES PARA LA COMPARACION 

--MOSTRAR LOS EMPLEADOS DEL DEPARTAMENTO 10 

select * from EMP where DEPT_NO = 10 

--NO DEBEMOS TENER VICIOS.  EXISTEN CONSULTAS QUE PUEDEN FUNCIONAR 

--PERO QUE NO SON STANDARD 

--MOSTRAR LOS EMPLEADOS QUE NO SEAN DEL DEPARTAMENTO 10 

select * from EMP where DEPT_NO <> 10 

select * from EMP where DEPT_NO != 10 --NO ES STANDARD 

--SQL SERVER, POR DEFECTO, NO ES CASE SENSITIVE EN LOS DATOS 

--MOSTRAR TODOS LOS EMPLEADOS CON OFICIO VENDEDOR 

select * from EMP where OFICIO = 'VENDEDOR' 

select * from EMP where OFICIO = 'vendedor' 

--OPERADORES RELACIONALES 

/* 

and: TODAS LAS CONDICIONES DEBEN CUMPLIRSE 

or: MUESTRA CUALQUIER CONDICION QUE SE CUMPLA 

not: MUESTRA LO CONTRARIO A UNA CONDICION.  EVITARLO 

*/ 

--MOSTRAR TODOS LOS EMPLEADOS CON OFICIO ANALISTA Y QUE COBREN  

--MAS DE 300.000 

select * from EMP where OFICIO = 'ANALISTA' and SALARIO > 300000 

--MOSTRAR TODOS LOS EMPLEADOS DEL DEPARTAMENTO 10 Y DEL 20 

select * from EMP where DEPT_NO = 10 or DEPT_NO = 20 

--MOSTRAR TODOS LOS EMPLEADOS CUYO OFICIO SEA DISTINTO A ANALISTA 

select * from EMP where not OFICIO = 'ANALISTA'  

select * from EMP where OFICIO <> 'ANALISTA' --EFICIENCIA 

--OTROS OPERADORES 

--OPERADOR BETWEEN BUSCA COINCIDENCIAS ENTRE RANGOS INCLUSIVE 

--MOSTRAR TODOS LOS EMPLEADOS CUYO SALARIO ESTE ENTRE 104.000 Y  

--200.000 

select * from EMP where SALARIO between 104000 and 200000 

select * from EMP where SALARIO >= 104000 and SALARIO <= 200000 

--OPERADOR IN 

--BUSCA COINCIDENCIAS DENTRO DE UN MISMO CAMPO CON DISTINTOS VALORES 

--ES COMO UTILIZAR UN OR CON UN CAMPO SOLAMENTE 

--MOSTRAR TODOS LOS EMPLEADOS DEL DEPARTAMENTO 10 Y DEL 20 y DEL 30 

--, 44, 55, 89 

select * from EMP where DEPT_NO = 10 or DEPT_NO = 20 

or DEPT_NO = 30 or DEPT_NO = 44  

or DEPT_NO = 55 or DEPT_NO = 89  

select * from EMP where DEPT_NO in (10, 20, 30, 44, 55, 89) 

--OPERADOR NOT IN QUE ES IGUAL, PERO MOSTRANDO LOS CONTRARIOS 

--MOSTRAR TODOS LOS EMPLEADOS QUE NO SEAN 

--DEL DEPARTAMENTO 10 Y DEL 20 

select * from EMP where not DEPT_NO in (10, 20) --MAL 

select * from EMP where DEPT_NO not in (10, 20) 

--OPERADOR LIKE 

--SIRVE PARA BUSCAR COINCIDENCIAS EN CADENAS 

--MEDIANTE ALGUNOS COMODINES NOS PERMITE BUSCAR CONTENIDO EN TEXTO 

-- % BUSCA CUALQUIER CARACTER/LONGITUD 

-- _ BUSCA UN SOLO CARACTER CUALQUIERA 

-- ? BUSCA UN SOLO CARACTER NUMERICO 

--MOSTRAR TODOS LOS EMPLEADOS QUE COMIENCEN POR LA LETRA S 

select * from EMP where APELLIDO like 'S%' 

--MOSTRAR TODOS LOS EMPLEADOS CON APELLIDOS DE 4 LETRAS 

select * from EMP where APELLIDO like '____' 

--CAMPOS CALCULADOS 

--SON COLUMNAS GENERADAS A PARTIR DE OTROS DATOS MEDIANTE  

--ALGUN CALCULO 

--SIEMPRE DEBEN TENER UN ALIAS EN LA CONSULTA 

--DICHO ALIAS/NAME NO PUEDE ESTAR REPETIDO EN UN CURSOR. 

--MOSTRAR EL APELLIDO Y EL SUELDO TOTAL (SALARIO + COMISION) 

--DE TODOS LOS EMPLEADOS 

select APELLIDO, SALARIO + COMISION as SUELDOTOTAL from EMP 

--NO PODEMOS UTILIZAR where CON EL ALIAS DE UN CAMPO CALCULADO 

--SI PODEMOS UTILIZAR order by 

--where: SE BASA EN LOS DATOS DE LA  TABLA. 

--DEBEMOS REALIZAR EL MISMO CALCULO DEL CAMPO EN EL where 

--order by: SE BASA EN ORDENAR EL CURSOR 

select APELLIDO, SALARIO + COMISION as SUELDOTOTAL from EMP 

order by SUELDOTOTAL 

--MOSTRAR EL APELLIDO Y EL SUELDO TOTAL (SALARIO + COMISION) 

--DE TODOS LOS EMPLEADOS QUE COBREN MAS DE 300.000 

select APELLIDO, SALARIO + COMISION as SUELDOTOTAL from EMP 

where SALARIO + COMISION > 300000 order by SUELDOTOTAL 

--CLAUSULA DISTINCT 

--ELIMINA REPETIDOS EN COLUMNAS EN UNA CONSULTA. 

--SE SUELE UTILIZAR CON POCAS COLUMNAS (UNA O DOS...) 

select distinct OFICIO from EMP 