--CONSULTAS DE AGRUPACION
--MOSTRAR EL MAXIMO SALARIO Y EL MINIMO SALARIO DE LOS EMPLEADOS
select MAX(SALARIO) as MAXIMO, MIN(SALARIO) as MINIMO from EMP;

--LAS CONSULTAS DE AGRUPACION SE PUEDEN BASAR EN TODA LA TABLA.
-- EN ALGUNOS CAMPOS.
--SI SE BASAN EN CAMPOS, DEBEMOS UTILIZAR group by CAMPO/s.
--SEA UNA FUNCION
-- DEBEMOS SABEER EL NUMERO DE EMPLEADOS POR CADA OFICIO
select COUNT(*) as EMPLEADOS, OFICIO from EMP
group by OFICIO;
--MOSTRAR EL SALARIO MAXIMO DE LOS EMPLEADOS POR CADA
--OFICIO Y DEPARTAMENTO
SELECT MAX(SALARIO) AS MAXIMOSSALARIO, OFICIO, DEPT_NO
FROM EMP
GROUP BY OFICIO, DEPT_NO;
-- FILTROS EN AGRUPACIONES
--WHERE: SE APLICA SOBRE LOS DATOS DE LA TABLA (ANTES DEL GROUP BY)
--HAVING: SE APLICA SOBRE LSO DATOS AGRUPTADOS (DESPUES DEL GROUP BY)
--MOSTRAR EL NUMERO DE EMPLEADOS POR DEPARTAMENTO QUE SEAN DIRECTORES
SELECT COUNT(*) AS EMPLEADOS, DEPT_NO
FROM EMP
WHERE OFICIO = 'DIRECTOR'
GROUP BY DEPT_NO
--mostrar el numero por departamento pero solamente de los empleados del departamento 10 y del 20;
SELECT COUNT(*) AS EMPLEADOS, DEPT_NO
FROM EMP
WHERE DEPT_NO = 10 or DEPT_NO = 20
GROUP BY DEPT_NO
--HAVING DEPT_NO = 10 or DEPT_NO = 20 -- ESTA ES UNA FORMA MAS EFICIENTE DE HACERLO

--MOSTRAR EL NUMER ODE EMPLEADOS POR DEPARTAMENTO DONDE EXISTAN 2 O MAS PERSONAS TRABAJANDO
SELECT COUNT(*) AS EMPLEADOS, DEPT_NO
FROM EMP
GROUP BY DEPT_NO
HAVING COUNT(*) >= 3

--CONSULTAS DE COMBINACION (IMPORTANTES) 
--Las consultas de combinación nos permiten mostrar datos de dos o más tablas dentro de un mismo  
--Cursor siempre que estén relacionadas entre sí. 
--Dependiendo del tipo de combinación, mostrará unos datos u otros. 

SELECT EMP.APELLIDO, EMP.OFICIO, DEPT.LOC
FROM EMP, DEPT
WHERE EMP.DEPT_NO = DEPT.DEPT_NO

--Con JOIN
SELECT EMP.APELLIDO, EMP.OFICIO, DEPT.LOC
from EMP 
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO

--REDUCIR NOMBRES
SELECT EMP.APELLIDO, EMP.OFICIO, DEPT.LOC
FROM EMP
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
where DEPT.LOC = 'MADRID'

--MOSTRAR LA SUMA SALARIAL DE TODOS LOS EMPLEADOS POR CADA CIUDAD
SELECT SUM(EMP.SALARIO) AS SUMASALARIAL, DEPT.LOC
FROM EMP
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
GROUP BY DEPT.LOC

--VAMOS A MOSTRAR ESTADO DE DOS CONSULTAS
SELECT * FROM DEPT
SELECT DISTINCT DEPT_NO FROM EMP

--TIPOS DE JOIN
--MOSTRAR TODOS LOS EMPLEADOS AUN QUE NO TENGAN DEPARTAMENTO
SELECT EMP.APELLIDO, EMP.OFICIO, DEPT.LOC
FROM EMP
LEFT JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
--MOSTRAR TODOS LOS DEPARTAMENTOS AUN QUE NO TENGAN EMPLEADOS
SELECT EMP.APELLIDO, EMP.OFICIO, DEPT.LOC
FROM EMP
RIGHT JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
--MOSTRAR TODOS AUN QUE TENGA NULL
SELECT EMP.APELLIDO, EMP.OFICIO, DEPT.LOC
FROM EMP
FULL JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
--COMBINACION DE DEPORTES
SELECT EMP.APELLIDO, EMP.OFICIO, DEPT.LOC
FROM EMP
CROSS JOIN DEPT
--SACAR NUMERO DE TRABAJADORES EN CADA DEPARTAMENTO
SELECT DEPT.DNOMBRE, COUNT(EMP.APELLIDO) AS TRABAJADORES
FROM DEPT
lEFT JOIN EMP
ON EMP.DEPT_NO = DEPT.DEPT_NO
GROUP BY DEPT.DNOMBRE
--JOINS DE 3 TRABLAS
SELECT PLANTILLA.APELLIDO, PLANTILLA.FUNCION, HOSPITAL.NOMBRE, HOSPITAL.DIRECCION, SALA.NOMBRE
FROM HOSPITAL
INNER JOIN PLANTILLA
ON HOSPITAL.HOSPITAL_COD = PLANTILLA.HOSPITAL_COD
INNER JOIN SALA
ON HOSPITAL.HOSPITAL_COD = SALA.HOSPITAL_COD
AND PLANTILLA.SALA_COD = SALA.SALA_COD

--Seleccionar el apellido, oficio, salario, numero de departamento y su nombre de todos los empleados cuyo salario sea mayor de 300000 
SELECT EMP.APELLIDO, EMP.OFICIO, EMP.SALARIO, DEPT.DEPT_NO, DEPT.DNOMBRE
FROM EMP
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
WHERE EMP.SALARIO > 300000

--Mostrar todos los nombres de Hospital con sus nombres de salas correspondientes. 
SELECT SALA.NOMBRE AS NOMBRE_SALA, HOSPITAL.NOMBRE AS NOMBRE_HOSPITAL
FROM SALA
INNER JOIN HOSPITAL
ON SALA.HOSPITAL_COD = HOSPITAL.HOSPITAL_COD

SELECT * FROM EMP

--Visualizar cuantas personas realizan cada oficio en cada departamento mostrando el nombre del departamento. 
SELECT DEPT.DNOMBRE, COUNT(*) AS N_PERSONAS, EMP.OFICIO
FROM EMP
RIGHT JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
GROUP BY DEPT.DNOMBRE, EMP.OFICIO