--Inserts

-- 1) Todas las columnas
insert into DEPT values (50, 'Informatica', 'OVIEDO')
-- 2) Algunos campos solamente
insert into DEPT (DEPT_NO, LOC)
VALUES (60, 'GUIJON')
-- 3) CON SUBCONSULTAS
SELECT * FROM DEPT
INSERT INTO DEPT VALUES
((SELECT MAX(DEPT_NO) + 1 FROM DEPT), 'I+D','TOLEDO')

-- 1) INSERT ..INTO
-- LA TABLA DESTINO DEBE EXISTIR Y TENER EL MISMO
-- NUMERO DE COLUMNAS Y TIPO DE DATO QUE LA TABLA ORIGEN
INSERT INTO DEPARTAMENTOS

-- 2) SELECT ..INTO
-- CREA UNA TABLA DESTINO, PERO SOLAMENTE LO PODEMOS REALIZAR UNA VEZ
SELECT * INTO DEPARTAMENTOS
FROM DEPT
-- ELIMINAR LOS REGISTROS DE TOLEDO
DELETE FROM DEPT WHERE LOC = 'TOLEDO'

--QUEREMOS ELIMINAR EL DATO NULL DE NUESTRA TABLA
-- SI QUEREMOS ACCEDER A UN NULL SE UTILIZA OPERADOR IS
DELETE FROM DEPT WHERE DNOMBRE IS NULL

--ELIMINAR EMPLEADOS DE OVIEDO
DELETE FROM EMP WHERE EMP.DEPT_NO = (SELECT DEPT_NO FROM DEPT WHERE LOC = 'OVIEDO')

--UPDATE
UPDATE DEPT SET LOC = 'SORIA'
WHERE LOC = 'ELCHE'

--ACTUALIZAR SALARIO POR OFICIOS
UPDATE EMP SET SALARIO = SALARIO + 1
WHERE OFICIO = 'DIRECTOR'
SELECT * FROM EMP

--Modifcar el salario de los empleados de soria y ponerles el mismo salario que arroyo
UPDATE EMP 
SET SALARIO = (SELECT SALARIO FROM EMP WHERE APELLIDO = 'ARROYO') 
WHERE DEPT_NO = (SELECT DEPT_NO FROM DEPT WHERE LOC = 'MADRID')
 
 SELECT * FROM EMP