--Las subconsultas se anidan entre parentesis y se igualan al resultado de la otra consulta
select * from EMP WHERE SALARIO = (SELECT MAX(SALARIO) FROM EMP)
-- SI LAS CONSULTAS ANIDADAS DEVUELVEN MAS DE UN VALOR SE UTILIZA EL OPERADOR IN
-- PARA LA COMPARACION

--MOSTRAR TODOS LOS EMPLEADOS QUE TENGAN EL MISMO OFICIO QUE SANCHA
SELECT * FROM EMP WHERE OFICIO = (SELECT OFICIO FROM EMP WHERE APELLIDO = 'SANCHA')
SELECT * FROM EMP WHERE OFICIO IN (SELECT OFICIO FROM EMP WHERE APELLIDO = 'SANCHA' OR APELLIDO = 'ARROYO')

--CONSULTAS UNION
-- UNA CONSULTA UNION MUESTRA EN UN MISMO CURSOR LOS DATOS DE VARIAS CONSULTAS
-- PARA PODER REALIZAR ESTAS CONSULTAS NECESITAMOS 3 REGLAS
-- 1 LA PRIMERA CONSULTA ES LA JEFA
-- 2 TODAS LAS CONSULTAS DEBEN TENER EL MISMO NUMERO DE COLUMNAS
-- 3 TODAS LAS COLUMNAS DE CADA CONSULTA DEBEN TENER EL MISMO TIPO DE DATO ENTRE SI
SELECT APELLIDO, OFICIO, SALARIO AS SUELDO, 'EMP' as TABLA FROM EMP WHERE SALARIO >= 220000
UNION 
SELECT APELLIDO, FUNCION, SALARIO, 'Plantilla' FROM PLANTILLA WHERE SALARIO >= 220000
UNION
SELECT APELLIDO, ESPECIALIDAD, SALARIO, 'Doctor' FROM DOCTOR WHERE SALARIO >= 220000

-- PARA MOSTRAR REPETIDOS EN UNA TABLA ES UNION ALL
SELECT APELLIDO, SALARIO FROM EMP
UNION ALL
SELECT APELLIDO, SALARIO FROM EMP

--PAGINACION DAR ALIAS A CAMPOS COMPARTIDOS
SELECT * FROM
(SELECT APELLIDO, OFICIO, SALARIO AS SUELDO, 'EMP' as TABLA FROM EMP
UNION 
SELECT APELLIDO, FUNCION, SALARIO, 'Plantilla' FROM PLANTILLA
UNION
SELECT APELLIDO, ESPECIALIDAD, SALARIO, 'Doctor' FROM DOCTOR) QUERY
WHERE QUERY.SUELDO >= 220000

--SWITCH Y FORMATOS EN SQL
SELECT APELLIDO, FUNCION, 
CASE T WHEN 'T' THEN 'TARDE' WHEN 'M' THEN 'MAÑANA' ELSE 'NOCHE'
END AS TURNO, T, SALARIO 
FROM PLANTILLA