--CREAMOS LA VISTA DE EMPLEADOS
--SIN SALARIO NI COMISION
-- CONSULTA VISTA ALMACENADA:    CREATE VIEW V_EMPLEADOS
-- CONSULTA VISTA ALMACENADA:    AS
-- CONSULTA VISTA ALMACENADA:		SELECT EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, DEPT_NO
-- CONSULTA VISTA ALMACENADA:		FROM EMP
-- CONSULTA VISTA ALMACENADA:    GO
SELECT * FROM V_EMPLEADOS

--PODEMOS INSERTAR VALORES EN ESTA VISTA SIN NECESIDAD DE TENER VALORES QUE NO SEAN OBLIGATORIOS
INSERT INTO V_EMPLEADOS VALUES
(112, 'VIEW', 'VIEW', 7902, GETDATE(), 10)

SELECT * FROM EMP

--PODEMOS CREAR UNA VISTA PARA VER LOS CAMPOS DE LAS TABLAS QUE DESEAMOS
create view V_EMP_DEPT
AS
	SELECT EMP.EMP_NO, EMP.APELLIDO, EMP.OFICIO,EMP.SALARIO,
	DEPT.DNOMBRE AS DEPARTAMENTO, DEPT.LOC AS LOCALIDAD
	FROM EMP
	INNER JOIN DEPT
	ON EMP.DEPT_NO = DEPT.DEPT_NO
GO

--INCREMENTAMOS EL SALARIO DE LOS EMPLEADOS DE SORIA
UPDATE V_EMP_DEPT SET SALARIO = SALARIO + 1 WHERE LOCALIDAD = 'SORIA'

--PORDIAMOS CAMBIAR EL NOMBRE DE LA LOCALIDAD
UPDATE V_EMP_DEPT SET LOCALIDAD = 'ALICANTE'
WHERE LOCALIDAD = 'MADRID'

--NO PODEMOS CAMBIAR MULTIPLES ELEMENTOS QUE AFECTEN A DOS TABLAS (NECESITA TRIGGERS)
UPDATE V_EMP_DEPT SET LOCALIDAD = 'ELCHE', SALARIO = SALARIO +1
WHERE LOCALIDAD = 'ALICANTE'

--NO SE PUEDE BORRAR EN ESTA VISTA POR QUE HAY VARIAS TABLAS (NECESITA TRIGGERS)
DELETE FROM V_EMP_DEPT WHERE LOCALIDAD = 'MADRID'

SELECT * FROM V_EMP_DEPT

--TRANSACT SQL
DECLARE @NUMERO INT
DECLARE @FECHA DATETIME
DECLARE @MENSAJE NVARCHAR(50)

--INICIAR CON SET
SET @NUMERO = 14
SET @FECHA = GETDATE()

--REPRESENTAR VALORES POR PANTALLA
--1) SELECT: UN SELECT REPRESENTA VARIABLES Y NOS PERMITE RECUPERARLAS
--			MEDIANTE UN READER EN ALGUN PROGRAMA
--2) PRINT: UN PRINT SIRVE PARA MSOTRAR MENSAJES DE SEGUIMIENTO DE 
-- ACCIONES EN LA BASE DE DATOS, ESTO RECUPERA DE FORMA "ESPECIAL" CON ALGUN PROGRAMA
PRINT @NUMERO
--SI COMBINAMOS VARIAS VARIABLES, DEBEMOS UTILIZAR CASTING
SET @MENSAJE = 'HOY ES MARTES '
PRINT @MENSAJE + CAST(@NUMERO AS NVARCHAR)

SELECT @MENSAJE, @NUMERO

--ALMACENAR VALORES EN VARIABLES A PARTIR DE CONSULTAS
--MOSTRAR EL EMPLEADO MAS ANTIGUO DE LA EMPRESA
SELECT * FROM EMP WHERE FECHA_ALT = (SELECT MIN(FECHA_ALT) FROM EMP)
--PODRIAMOS ALMACENAR EL DATO DE MIN EN UNA VARIABLE Y EJECUTAR LA CONSULTA
DECLARE @FECHAALT DATETIME
--SELECT @VARIABLE = VALOR, @VARIABLE = VALOR FORM TABLA
SELECT @FECHAALT = MIN(FECHA_ALT) FROM EMP
PRINT @FECHAALT
SELECT * FROM EMP WHERE FECHA_ALT = @FECHAALT
--CONDICIONALE SE UTILIZAN LOS MISMOS OPEREADORES

/*
IF(CONDICION)
BEGIN
	--CONDICION TRUE
END
ELSE IF (CONDICION b)
BEGIN
	--CONDICION b
END
ELSE
BEGIN
	--CONDICION ELSE
END
*/
--NUMERO POSITIVO / NEGATIVO / CERO
DECLARE @NUM INT
SET @NUM = 9
IF (@NUM > 0)
BEGIN
	PRINT 'POSITIVO'
END
ELSE IF (@NUM < 0)
BEGIN
	PRINT 'NEGATIVO'
END
ELSE
BEGIN
	PRINT 'CERO'
END

--MOSTRAR LOS EMPLEADOS DEL DEPARTAMENTO DE CONTABILIDAD
--SI NO EXISTE EL DEPARTAMENTO, MOSTRAMOS UN MENSAJE
DECLARE @DEPTNO INT
SELECT @DEPTNO = DEPT_NO FROM DEPT
WHERE DNOMBRE = 'CONTABILIDAD'

IF (@DEPTNO = 0)
BEGIN
	PRINT 'NO EXISTE LE DEPARTAMENTO'
END
ELSE
BEGIN
	SELECT * FROM EMP WHERE DEPT_NO = @DEPTNO
END

--modificar el salario de un empleado(SANCHA)
-- SI COBRA MENOS DE 150000, SUBIMOS EL SALARIO EN 2.000
--SI COBRA MAS DE 150000, BAJAMOS EL SALARIO EN 2.000
DECLARE @SALARIO INT
SELECT @SALARIO = SALARIO FROM EMP WHERE APELLIDO = 'SANCHA'

IF (@SALARIO > 150000)
BEGIN
	UPDATE EMP SET SALARIO = SALARIO - 2000
	WHERE APELLIDO = 'SANCHA'
	PRINT 'BAJAMOS SUELDO'
END
ELSE
BEGIN
	UPDATE EMP SET SALARIO = SALARIO + 2000
	WHERE APELLIDO = 'SANCHA'
	PRINT 'SUBIMOS SUELDO'
END
SELECT * FROM EMP WHERE APELLIDO = 'SANCHA'

--MODIFICAR EL SALARIO DE LOS EMPLEADOS DE LA PLANTILLA
-- DE LA PAZ
-- SI LA SUMA SALARIAL SUPERA 1.000.000, BAJAMOS EL SALARIO EN 10.000
-- A TODOS
-- SI LA SUMA SALARIAL NO SUPERA 1.000.000, SUBIMOS EL SALARIO EN 10.000
-- A TODOS
-- MOSTRAMOS QUE ACCIONES ESTAMOS HACIENDO
DECLARE @SALARIOGENERAL INT
SELECT @SALARIOGENERAL = SALARIO FROM PLANTILLA
IF (@SALARIOGENERAL > 1000000)
BEGIN
	UPDATE PLANTILLA SET SALARIO = SALARIO - 10000 WHERE HOSPITAL_COD = 22
	PRINT 'BAJAMOS EL SALARIO A TODA LA PLANTILLA'
	SELECT * FROM PLANTILLA WHERE HOSPITAL_COD = 22
END
ELSE
BEGIN
	UPDATE PLANTILLA SET SALARIO = SALARIO + 10000 WHERE HOSPITAL_COD = 22
	PRINT 'SUBIMOS EL SALARIO A TODA LA PLANTILLA'
	SELECT * FROM PLANTILLA WHERE HOSPITAL_COD = 22
END

--LOS BUCLES NO SON HERRAMIENTAS DE PROGRAMACION
-- DNTRO DE LAS BBDD.
-- LOS BUCLES SOLAMENTE SE UTILIZAN COMO CURSORES
DECLARE @CONTADOR INT
SET @CONTADOR = 1
WHILE (@CONTADOR <= 10)
BEGIN
	PRINT 'CONTADOR ' + CAST (@CONTADOR NVARCHAR)
	SET @CONTADOR = @CONTADOR + 1
END
--BUCLE SE UTILIZAN CON CURSORES
--ALMACENAR EL APELLIDO DE TODOS LOS EMPLEADOS EN UN CURSOR
DECLARE @APE NVARCHAR(50)
SELECT @APE = APELLIDO FROM EMP
PRINT @APE
--SI NECESITAMOS RECORRER CADA UNO DE LOS DATOS, DEBEMOS HACERLO CON UN CURSOR
DECLARE @APELLIDO NVARCHAR(50)
DECLARE @OFICIO NVARCHAR(50)
--1) DELCARAR EL CURSOR COMO CONSULTA EN UNA VARIABLE
DECLARE QUERY CURSOR FOR
SELECT APELLIDO, OFICIO FROM EMP
--2) ABRIR EL CURSOR
OPEN QUERY
--3) MOVER UNA POSICION DENTRO DEL CURSOR
FETCH NEXT FROM QUERY INTO @APELLIDO, @OFICIO
-- UNA VEZ QUE ESTAMOS POSICIONADOS, EXISTE UNA VARIABLE DE SISTEMA
-- @@FETCH_STATUS QUE INDICA SI HEMOS LLEGAOD AL FINAL DEL CURSOR
--SI EXISTEN REGISTROS = 0
--4) BUCLE DE LECTURA DE REGISTROS
WHILE (@@FETCH_STATUS = 0)
BEGIN
	PRINT @APELLIDO + ' ' + @OFICIO
	--DEBEMOS MOVERNOS FILA A FILA
	FETCH NEXT FROM QUERY INTO @APELLIDO, @OFICIO
END
--5) CERRAR EL CURSROR
CLOSE QUERY
--6) LIBERAR EL CURSOR  DE LA MEMORIA
DEALLOCATE QUERY

--PRECEDIMIENTOS ALMACENADOS

CREATE PROCEDURE SP_BUSCADOR_EMP_SALARIO
(@SALARIO INT)
AS
	SELECT * FROM EMP
	WHERE SALARIO > @SALARIO
GO

--PODEMOS TENER VARIABLES Y CUALQUIER TIPO DE CONSULTA
--PROCEDIMIENTO PARA INSERTAR UN DEPARTAMENTO
--GENERAR EL ID DE FORMA AUTOMATICA CON EL PROCEDIMIENTO
CREATE PROCEDURE SP_INSERT_DEPT(@NOMBRE NVARCHAR(50), @LOCALIDAD NVARCHAR(50))
AS
	DECLARE @ID INT
	SELECT @ID = MAX(DEPT.DEPT_NO) + 1 FROM DEPT
	INSERT INTO DEPT VALUES (@ID, @NOMBRE, @LOCALIDAD)
GO
EXECUTE SP_INSERT_DEPT 'STORED', 'PROCEDURE'

--PROCEDIMIENTO PARA MODIFICAR EL SALARIO
CREATE PROCEDURE SP_MODIFICAR_SALARIO_EMP
(@apellido nvarchar(50))
AS
BEGIN
    DECLARE @salario INT

    -- Obtenemos el salario actual del empleado
    SELECT @salario = SALARIO FROM EMP
    WHERE APELLIDO = @apellido

    -- Lógica de modificación
    IF (@salario > 150000)
    BEGIN
        UPDATE EMP SET SALARIO = SALARIO - 2000
        WHERE APELLIDO = @apellido
        PRINT 'bajamos sueldo'
    END
    ELSE
    BEGIN
	UPDATE EMP SET SALARIO = SALARIO + 2000
        WHERE APELLIDO = @apellido
        PRINT 'bajamos sueldo'
        PRINT 'el sueldo sube'
    END
END

--NECESITAMOS INCREMENTR EL SALARIO DE LOS DOCTORES DE UNA ESPECIALIDAD
--EL INCREMENTO SERA UN VALOR QUE NOSOTROS ENVIAREMOS A NUESTRO PROCEDIMIENTO
--CADA DOCTOR DEBE TENER UN VALOR DE INCREMENTO DISTINTO
--SELECT RAND() * 80
--UPDATE DOCTOR SET SALARIO = SALARIO + 69
--WHERE ESPECIALIDAD = 'NEUROLOGIA'

CREATE PROCEDURE INCREMENTAR_SALARIO_ESPECIALIDAD (@ESPECIALIDAD NVARCHAR(50))
AS
BEGIN
    -- Declaramos variables para guardar los datos de cada fila
    DECLARE @ID_DOCTOR INT
    DECLARE @INCREMENTO INT
    -- 1. El cursor debe seleccionar a los doctores de esa especialidad 
    -- y necesitamos su ID (HOSPITAL_COD o DOCTOR_NO) para poder actualizarlos
    DECLARE BUCLEDOCTOR CURSOR FOR
    SELECT DOCTOR_NO FROM DOCTOR 
    WHERE ESPECIALIDAD = @ESPECIALIDAD
    OPEN BUCLEDOCTOR
    -- 2. Leemos el primer registro
    FETCH NEXT FROM BUCLEDOCTOR INTO @ID_DOCTOR
    WHILE (@@FETCH_STATUS = 0)
    BEGIN
        -- 3. Generamos un incremento aleatorio distinto en cada vuelta
        SET @INCREMENTO = RAND() * 1000
        -- 4. Actualizamos SOLO al doctor actual usando su ID
        UPDATE DOCTOR 
        SET SALARIO = SALARIO + @INCREMENTO 
        WHERE DOCTOR_NO = @ID_DOCTOR
        -- 5. MUY IMPORTANTE: Leer el siguiente registro para no crear un bucle infinito
        FETCH NEXT FROM BUCLEDOCTOR INTO @ID_DOCTOR
    END
    -- 6. Limpieza
    CLOSE BUCLEDOCTOR
    DEALLOCATE BUCLEDOCTOR
END
GO

EXECUTE INCREMENTAR_SALARIO_ESPECIALIDAD 'Psiquiatría'

SELECT * FROM DOCTOR WHERE ESPECIALIDAD = 'Psiquiatría'