--CREAMOS LA VISTA DE EMPLEADOS
--SIN SALARIO NI COMISION
-- CONSULTA VISTA ALMACENADA:    CREATE VIEW V_EMPLEADOS
-- CONSULTA VISTA ALMACENADA:    AS
-- CONSULTA VISTA ALMACENADA:		SELECT EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, DEPT_NO
-- CONSULTA VISTA ALMACENADA:		FROM EMP
-- CONSULTA VISTA ALMACENADA:    GO
SELECT * FROM V_EMPLEADOS

INSERT INTO V_EMPLEADOS VALUES
(112, 'VIEW', 'VIEW', 7902, GETDATE(), 10)

SELECT * FROM EMP